add rattler_auth to authenticate requests
mamba-org/rattler pull request #191
Opened 2023-05-07 15:11 UTC by wolfv

2023-05-07 15:13 UTC, wolfv commented
@baszalmstra unfortunately I had to make two functions, one for `reqwest::blocking::Client` and one for `reqwest::Client`. Maybe you have an idea on how to improve this?

Apart from that it works like a charm :)

2023-05-07 20:54 UTC, baszalmstra requested changes
Nice work!

Some comments:

* authentication is currently a singleton and it cant be turned on or off. I dont like how intransparent, uncontrollable and potentially thread unsafe it is. It would be nice if you pass in an object for authentication.  There you could also specify the key for the keychain for instance. Authentication::from_keychain would be nice to have!

* Please dont use unwrap in library code unless you are sure the code cannot fail. And even then, please add a comment and/or use expect.

2023-05-07 20:54 UTC, baszalmstra commented on crates/rattler_auth/src/lib.rs
> +            let password = format!("Bearer {}", token);
Can you implement Display? Since you also implement FromStr it makes sense to be able to convert from String and back.

2023-05-07 20:54 UTC, baszalmstra commented on crates/rattler_auth/src/lib.rs
> +    let entry = Entry::new("rattler_auth", host).unwrap();
Return error instead of unwrap

2023-05-07 20:54 UTC, baszalmstra commented on crates/rattler_auth/src/lib.rs
> +pub fn authenticated_request<U: IntoUrl>(client: &Client, url: U) -> reqwest::RequestBuilder {
Maybe take a requestbuilder as input? That way the user is in charge of the entire request construction.

2023-05-07 20:54 UTC, baszalmstra commented on crates/rattler_auth/src/lib.rs
> +    let authentication = get_authentication(host).unwrap();
Please return sensible errors instead of unwrap.

2023-05-07 20:54 UTC, baszalmstra commented on crates/rattler_auth/src/lib.rs
> +    println!("Getting authenticated request for host: {}", host);
Please you tracing instead of println

2023-05-15 15:38 UTC, baszalmstra reviewed
This looks pretty close to done to me! A note:

* Since you can only really use an `AuthenticatedClient` and there is no `UnauthenticatedClient` maybe we can just call it `Client`?
* I think by `Default` the "client" should be unauthenticated unless you initialize it with credentials. See my other comment.
* It would be very nice if there is also a `From<reqwest::Client>` implementation. That way the library remains super simple to use with just reqwest.
* Random thought: If there is direct conversion from `reqwest::Client` to `rattler_networking::Client` we can use `impl Into<rattler_networking::Client>` as an argument where authentication is required. That way people can keep using the `reqwest::Client` too.

2023-05-15 15:38 UTC, baszalmstra commented on crates/rattler_networking/src/lib.rs
> +    pub fn store(&self, host: &str, authentication: &Authentication) -> keyring::Result<()> {
Im wondering, should this be mutable?

2023-05-15 15:38 UTC, baszalmstra commented on crates/rattler_networking/src/lib.rs
> +    pub fn get(&self, host: &str) -> Result<Option<Authentication>, AuthenticationStorageError> {
I think `try_get` would be better here because it returns an option.

2023-05-15 15:38 UTC, baszalmstra commented on crates/rattler_networking/src/lib.rs
> +            auth_storage: AuthenticationStorage::new("rattler"),
I think the `Default` implementation should be "unauthenticated". Using "rattler" as a default key means you are accessing a giant global variable that is used by everything that is using rattler which seems like a huge red-flag to me.

2023-05-15 18:56 UTC, wolfv commented
The idea of having a default key is that multiple tools could share the same namespace for credentials (eg rattler-build and px are both logged in to the same sites).

2023-05-15 19:08 UTC, baszalmstra commented
I think thats dangerous behavior because if you set certain (invalid) credentials it affects **all** programs that use the **default** behavior. Its worst kind of a global variable you can have..

To me its also not logical that if you would do ‘px login’ it also works with ‘rattler-build publish’ (or whatever). Id much rather have a seperate ‘rattler-build login’.

Ever more so as this is a library, I think we should allow users to opt-in by specifying the same key. It should not be the default behavior.

2023-05-15 19:43 UTC, wolfv commented
Hmm but for each channel you want to use with rattler build (not for publishing, just for pulling packages from) you'd need to re-login. A lot of programs use global configurations for credentials (eg netrc files) or global proxy configurations (HTTP_PROXY environment variable etc).

One can also easily opt out of the global sharing by using a different key. 

I think it would be pretty nice if px and rattler build share the credentials (which we can achieve either way).

2023-05-17 08:25 UTC, wolfv commented
just for the record, I am working on a keyring-rs compatible fallback storage that saves the authentication to a file in the `~/.rattler_auth.json` location (trying to make that configurable as well).

It's a bit challenging because of multi-threading and file locking but hopefully can get it done soon.

2023-06-06 07:41 UTC, baszalmstra approved these changes

2023-06-06 07:41 UTC, baszalmstra commented on crates/rattler-bin/src/commands/create.rs
> +    print!("Cache folder: {}", repodata_cache_path.display());
Left over debug statement?

2023-06-06 07:41 UTC, baszalmstra commented on crates/rattler_networking/src/authentication_storage/storage.rs
> +    pub fallback_json_location: PathBuf,
Why not use the `FallbackStorage` object here, instead of recreating it where you need it?

2023-06-06 15:15 UTC, baszalmstra approved these changes

2023-06-13 13:17 UTC, merged