ignore trailing .0 in version comparison
mamba-org/rattler pull request #196
Opened 2023-05-25 05:30 UTC by wolfv

Not sure if this is the cleanest way of implementing this behavior, but in order to fix #194 we need to ignore trailing `0` when comparing versions for equality.

2023-05-25 08:23 UTC, baszalmstra requested changes
Can this code also be found somewhere in the conda codebase? I followed that pretty closely.

2023-05-25 08:23 UTC, baszalmstra commented on crates/rattler_conda_types/src/version/mod.rs
>      fn eq(&self, other: &Self) -> bool {
Could you inplement this as the Eq trait of VersionComponent?

2023-05-25 08:23 UTC, baszalmstra requested changes
Can this code also be found somewhere in the conda codebase? I followed that pretty closely.

2023-05-25 08:49 UTC, wolfv commented
I can try to find the place in the conda code but this was an issue i observed while debugging resolvelib stuff

2023-05-25 19:35 UTC, wolfv commented
We actually did copy the docs for it! :) https://github.com/mamba-org/rattler/blob/001f326c7c3160637c8778c5a1c33f715266434e/crates/rattler_conda_types/src/version/mod.rs#L71-L72

2023-05-25 19:36 UTC, wolfv commented
And this is the code in conda: 


```python
    def _eq(self, t1, t2):
        for v1, v2 in zip_longest(t1, t2, fillvalue=[]):
            for c1, c2 in zip_longest(v1, v2, fillvalue=self.fillvalue):
                if c1 != c2:
                    return False
        return True
```

https://github.com/conda/conda/blob/61edfac743a2461a24fafe48b821a99af61b6bd4/conda/models/version.py#L244-L249

2023-05-25 19:39 UTC, wolfv commented
Btw. I think we're also missing an compare of the `epoch` of the two versions.

2023-05-25 21:26 UTC, wolfv commented
I am confused by the follownig:

```
    /// The epoch of this version. This is an optional number that can be used to indicate a change
    /// in the versioning scheme.
    norm: String,
```

The norm doesn't seem to be the epoch but rather the string representation of the version?

2023-05-25 21:32 UTC, wolfv commented
E.g. this is what I see in debug print:

```
Version { norm: "1.2.0", version: [[0], [1], [2], [0]], local: [] }
Version { norm: "1!1.2.3", version: [[1], [1], [2], [3]], local: [] }
```

2023-05-25 21:44 UTC, wolfv commented
I attempted what you asked but there I am a bit unsure about a couple things. 

I had to add `#[derive(Eq)]` to the `Version` for some reason.

Also I had to implement a custom hash function. I am now removing all default values (0) from the hash. Clippy was warning that the hash function needs to match the `PartialEq` function.

2023-05-26 10:42 UTC, baszalmstra commented
This looks good to me! The warning about the hash is also very correct! Very nice!

The `norm` is a bit of an odd duck. It represents "sorta" the string it was initially created from. This can be important because (as you've seen with this issue) multiple version representations can represent the exact same version. The `norm` sorta enables keeping track of that. However, modifications to the `Version` are also not expressed in the `norm` which is actually just plain wrong. Maybe we should remove it and implement a proper `Display` for `Version`.

2023-05-26 10:43 UTC, baszalmstra approved these changes

2023-05-26 10:43 UTC, merged