Add GCS support for rattler auth
mamba-org/rattler pull request #605
Opened 2024-04-17 00:23 UTC by clement-chaneching

Hello,

### Context
We would like to switch to pixi for our package manager.
We were thinking of having our private packages hosted on a private conda channel on Google Cloud Storage Buckets.
This change will allow pixi to automatically find the packages if we are logged in in our CLI

### Changes:
Change the auth to async for gcloud.
Use the google_cloud_auth module to login ( No need to pass any argument)
Added a test to validate the application_default_credentials path.

### Example pixi.toml:

```
channels = ["conda-forge","https://storage.googleapis.com/<bucket_name>]

[dependencies]
<private_module>= { version = "*", channel = "https://storage.googleapis.com/<bucket_name>" }

```
### Results
If not logged in:
![image](https://github.com/mamba-org/rattler/assets/151473645/141ee0bd-f0cc-4cc4-a4db-516db6ac36c4)
After running `gcloud auth application-default login`:
![image](https://github.com/mamba-org/rattler/assets/151473645/578f8b88-447c-439e-b6fa-fc306f154a08)

2024-04-17 07:08 UTC, baszalmstra requested changes
Thanks! This looks almost good to me!

2024-04-17 07:08 UTC, baszalmstra commented on crates/rattler_networking/Cargo.toml
> +google-cloud-auth = "0.13.2"
Could you add this as a workspace dependency? 

Google-cloud-auth also by default adds the default-tls features. Could you make the tls implementation configurable using the features of the crate?

2024-04-17 07:19 UTC, clement-chaneching commented
Need to fix test & linting

2024-04-18 00:59 UTC, clement-chaneching commented
Hello!
Thanks for your reactivity.
I am not sure what is failing in the CI since I didn't modify the tests and I can't find any logs in the failed step. 
Do you have any ideas on this?

2024-04-18 05:39 UTC, baszalmstra commented
I also cant see any logs. I restarted the job.

2024-04-18 06:22 UTC, wolfv commented on crates/rattler_networking/src/authentication_middleware.rs
> +            "https://www.googleapis.com/auth/devstorage.full_control",
Is this the lowest permission? I don't think we need full control all the time, right? Maybe read-only is possible?

2024-04-18 06:23 UTC, wolfv commented on crates/rattler_networking/src/authentication_middleware.rs
> +use google_cloud_auth::project::create_token_source;
do we need to make these `use` statements so that they are only enabled when the `google-cloud-auth` feature is enabled?

2024-04-18 06:25 UTC, wolfv commented on crates/rattler_networking/src/authentication_middleware.rs
> +        } else if req.url().host_str() == Some("storage.googleapis.com") {
For the `oci` registry support we came up with a new "scheme". I also know that conda has support for an `s3://` scheme. 

Maybe we could also decide that channels that are on Google Cloud should indicate that with a `gcs://storage.googleapis.com/bla`? 

Potentially, people could also have public buckets there (and no need for authentication?).

2024-04-19 06:27 UTC, clement-chaneching commented
Thanks for these comments!
We now specify gcs://<bucketname> instead of the storage.googelapis endpoint which is indeed more natural for gcs users:
![image](https://github.com/mamba-org/rattler/assets/151473645/70418bc7-5e0a-4f54-9dde-2b61ce35c01c)

I have added the google-cloud-auth package as a feature so the CI is now failing.
Is it the right way to do it?

2024-04-19 06:27 UTC, wolfv commented
Hi @clement-chaneching - this is starting to look good! Thanks for taking care of my comments. How annoyed would you be with one more idea? 
I think ideally, this would live in its own file and be a seperate middleware. Then it can be easily enabled (or disabled) by anyone. You already have the functionality done, so that's all fine. Basically you would just take your code, and put it in it's own `GCSMiddleware` struct. 

WDYT?

Otherwise happy to merge and make the changes later :)

2024-04-19 07:43 UTC, wolfv commented
@clement-chaneching the "conditional" inclusion will also be easier when it's in it's own file. Because we can just only include & expose it when the feature is enabled.

2024-04-19 07:44 UTC, clement-chaneching commented
Yep it does make sense.
However im not so familiar with rust so not sure how to do it.
I have started this PR to separate my file in a different middleware
https://github.com/clement-chaneching/rattler/pull/1

But not sure how to test it.
I would guess it s on this [pixi file](https://github.com/prefix-dev/pixi/blob/main/src/utils/reqwest.rs) but I cant make it work.

Could you help me on this? :)

2024-04-21 05:06 UTC, clement-chaneching commented
Great thanks it's working!

2024-04-22 23:27 UTC, clement-chaneching commented
@wolfv Thanks for your comments and your help!
I can test properly in pixi using:
```
#[cfg(feature = "google-cloud-auth")]
use rattler_networking::GCSMiddleware;
And
    #[cfg(feature = "google-cloud-auth")]
    {client_builder = client_builder.with(GCSMiddleware);}
```

Is there anything I need to modify to validate the CI?

2024-04-25 13:38 UTC, wolfv approved these changes
Let's merge this! :)

2024-04-25 13:41 UTC, merged